<?xml version="1.0" encoding="utf-8"?><Database Name="BSCKPI" Class="linqDanhMucBKDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.200.160;Initial Catalog=BSCKPI;Persist Security Info=True;User ID=chay" SettingsObjectName="DaoBSCKPI.Properties.Settings" SettingsPropertyName="BSCKPIConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_tblBKNhomDanhMuc_DanhSach" Method="sp_tblBKNhomDanhMuc_DanhSach">
    <ElementType Name="sp_tblBKNhomDanhMuc_DanhSachResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ma" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="STTsx" Type="System.Decimal" DbType="Decimal(8,1)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblBKDanhMuc_DanhSach" Method="sp_tblBKDanhMuc_DanhSach">
    <Parameter Name="Nhom" Parameter="nhom" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblBKDanhMuc_DanhSachResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ma" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenTat" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="STTsx" Type="System.Decimal" DbType="Decimal(8,1)" CanBeNull="true" />
      <Column Name="Nhom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NguoiTao" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DangSuDung" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>