<?xml version="1.0" encoding="utf-8"?><Database Name="BSCKPI" Class="linqChiTieuKPIDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.200.160;Initial Catalog=BSCKPI;Persist Security Info=True;User ID=chay" SettingsObjectName="DaoBSCKPI.Properties.Settings" SettingsPropertyName="BSCKPIConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_tblBKChiTieuKPI_DoiTrangThai" Method="sp_tblBKChiTieuKPI_DoiTrangThai">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="TrangThai" Parameter="trangThai" Type="System.Int32" DbType="Int" />
    <Parameter Name="NguoiThaoTac" Parameter="nguoiThaoTac" Type="System.String" DbType="NVarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblBKChiTieuKPI_GanVoiBSC" Method="sp_tblBKChiTieuKPI_GanVoiBSC">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDBSC" Parameter="iDBSC" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblBKChiTieuKPI_ThemSua" Method="sp_tblBKChiTieuKPI_ThemSua">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ma" Parameter="ma" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="STT" Parameter="sTT" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="Ten" Parameter="ten" Type="System.String" DbType="NVarChar(250)" />
    <Parameter Name="TrongSo" Parameter="trongSo" Type="System.Decimal" DbType="Decimal(22,3)" />
    <Parameter Name="MucTieu" Parameter="mucTieu" Type="System.Decimal" DbType="Decimal(22,3)" />
    <Parameter Name="IDDonViTinh" Parameter="iDDonViTinh" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDBSC" Parameter="iDBSC" Type="System.Int32" DbType="Int" />
    <Parameter Name="Muc" Parameter="muc" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDTanSuatDo" Parameter="iDTanSuatDo" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDXuHuongYeuCau" Parameter="iDXuHuongYeuCau" Type="System.Int32" DbType="Int" />
    <Parameter Name="STTsx" Parameter="sTTsx" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="InDam" Parameter="inDam" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="InNghieng" Parameter="inNghieng" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NguoiTao" Parameter="nguoiTao" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="TrangThai" Parameter="trangThai" Type="System.Int32" DbType="Int" />
    <Parameter Name="NguoiThaoTac" Parameter="nguoiThaoTac" Type="System.String" DbType="NVarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblBKChiTieuKPI_ThongTin" Method="sp_tblBKChiTieuKPI_ThongTin">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblBKChiTieuKPI_ThongTinResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ma" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="STT" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TrongSo" Type="System.Decimal" DbType="Decimal(22,3)" CanBeNull="true" />
      <Column Name="MucTieu" Type="System.Decimal" DbType="Decimal(22,3)" CanBeNull="true" />
      <Column Name="IDDonViTinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDBSC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Muc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDTanSuatDo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDXuHuongYeuCau" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STTsx" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="InDam" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="InNghieng" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NguoiTao" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NguoiSua" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayTrangThai" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NguoiThaoTac" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>