<?xml version="1.0" encoding="utf-8"?><Database Name="BSCKPI" Class="linqBangDanhGiaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.200.160;Initial Catalog=BSCKPI;Persist Security Info=True;User ID=chay" SettingsObjectName="DaoBSCKPI.Properties.Settings" SettingsPropertyName="BSCKPIConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_tblBKMauBangDanhGia_Bang" Method="sp_tblBKMauBangDanhGia_Bang">
    <Parameter Name="Thang" Parameter="thang" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="Nam" Parameter="nam" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDNhanVien" Parameter="iDNhanVien" Type="System.Guid" DbType="UniqueIdentifier" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_test" Method="sp_test">
    <ElementType Name="sp_testResult">
      <Column Name="IDNhom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenNhom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThuTu" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TrongSoNhom" Type="System.Decimal" DbType="Decimal(22,3)" CanBeNull="true" />
      <Column Name="MucTieu" Type="System.Decimal" DbType="Decimal(22,3)" CanBeNull="true" />
      <Column Name="TanSuatDo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TrongSo" Type="System.Decimal" DbType="Decimal(22,3)" CanBeNull="true" />
      <Column Name="KetQua" Type="System.Decimal" DbType="Decimal(22,3)" CanBeNull="true" />
      <Column Name="DienGiai" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="LoaiChiTieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STTsx" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="STT" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>