#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoBSCKPI.Database.CongViecCaNhan
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BSCKPI")]
	public partial class linqcvcnGiaHanDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public linqcvcnGiaHanDataContext() : 
				base(global::DaoBSCKPI.Properties.Settings.Default.BSCKPIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linqcvcnGiaHanDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqcvcnGiaHanDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqcvcnGiaHanDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqcvcnGiaHanDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblcvCongViecCaNhanGiaHan_Them")]
		public int sp_tblcvCongViecCaNhanGiaHan_Them([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaCongViecCaNhan", DbType="Decimal(20,0)")] System.Nullable<decimal> maCongViecCaNhan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HanNgayCu", DbType="Date")] System.Nullable<System.DateTime> hanNgayCu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HanGioCu", DbType="Time")] System.Nullable<System.TimeSpan> hanGioCu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HanNgayMoi", DbType="Date")] System.Nullable<System.DateTime> hanNgayMoi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HanGioMoi", DbType="Time")] System.Nullable<System.TimeSpan> hanGioMoi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LyDo", DbType="NVarChar(250)")] string lyDo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NguoiThucHien", DbType="UniqueIdentifier")] System.Nullable<System.Guid> nguoiThucHien)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCongViecCaNhan, hanNgayCu, hanGioCu, hanNgayMoi, hanGioMoi, lyDo, nguoiThucHien);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblcvCongViecCaNhanGiaHan_ThongTin")]
		public ISingleResult<sp_tblcvCongViecCaNhanGiaHan_ThongTinResult> sp_tblcvCongViecCaNhanGiaHan_ThongTin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaCongViecCaNhan", DbType="Decimal(20,0)")] System.Nullable<decimal> maCongViecCaNhan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanGiaHan", DbType="SmallInt")] System.Nullable<short> lanGiaHan)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCongViecCaNhan, lanGiaHan);
			return ((ISingleResult<sp_tblcvCongViecCaNhanGiaHan_ThongTinResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblcvCongViecCaNhanGiaHan_DanhSach")]
		public ISingleResult<sp_tblcvCongViecCaNhanGiaHan_DanhSachResult> sp_tblcvCongViecCaNhanGiaHan_DanhSach([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaCongViecCaNhan", DbType="Decimal(20,0)")] System.Nullable<decimal> maCongViecCaNhan)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCongViecCaNhan);
			return ((ISingleResult<sp_tblcvCongViecCaNhanGiaHan_DanhSachResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_tblcvCongViecCaNhanGiaHan_ThongTinResult
	{
		
		private decimal _MaCongViecCaNhan;
		
		private System.Nullable<System.DateTime> _HanNgayCu;
		
		private System.Nullable<System.TimeSpan> _HanGioCu;
		
		private System.Nullable<System.DateTime> _HanNgayMoi;
		
		private System.Nullable<System.TimeSpan> _HanGioMoi;
		
		private System.Nullable<short> _LanGiaHan;
		
		private string _LyDo;
		
		private System.Nullable<System.DateTime> _NgayThucHien;
		
		private System.Nullable<System.Guid> _NguoiThucHien;
		
		public sp_tblcvCongViecCaNhanGiaHan_ThongTinResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongViecCaNhan", DbType="Decimal(20,0) NOT NULL")]
		public decimal MaCongViecCaNhan
		{
			get
			{
				return this._MaCongViecCaNhan;
			}
			set
			{
				if ((this._MaCongViecCaNhan != value))
				{
					this._MaCongViecCaNhan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanNgayCu", DbType="Date")]
		public System.Nullable<System.DateTime> HanNgayCu
		{
			get
			{
				return this._HanNgayCu;
			}
			set
			{
				if ((this._HanNgayCu != value))
				{
					this._HanNgayCu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanGioCu", DbType="Time")]
		public System.Nullable<System.TimeSpan> HanGioCu
		{
			get
			{
				return this._HanGioCu;
			}
			set
			{
				if ((this._HanGioCu != value))
				{
					this._HanGioCu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanNgayMoi", DbType="Date")]
		public System.Nullable<System.DateTime> HanNgayMoi
		{
			get
			{
				return this._HanNgayMoi;
			}
			set
			{
				if ((this._HanNgayMoi != value))
				{
					this._HanNgayMoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanGioMoi", DbType="Time")]
		public System.Nullable<System.TimeSpan> HanGioMoi
		{
			get
			{
				return this._HanGioMoi;
			}
			set
			{
				if ((this._HanGioMoi != value))
				{
					this._HanGioMoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanGiaHan", DbType="SmallInt")]
		public System.Nullable<short> LanGiaHan
		{
			get
			{
				return this._LanGiaHan;
			}
			set
			{
				if ((this._LanGiaHan != value))
				{
					this._LanGiaHan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LyDo", DbType="NVarChar(250)")]
		public string LyDo
		{
			get
			{
				return this._LyDo;
			}
			set
			{
				if ((this._LyDo != value))
				{
					this._LyDo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThucHien", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayThucHien
		{
			get
			{
				return this._NgayThucHien;
			}
			set
			{
				if ((this._NgayThucHien != value))
				{
					this._NgayThucHien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThucHien", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> NguoiThucHien
		{
			get
			{
				return this._NguoiThucHien;
			}
			set
			{
				if ((this._NguoiThucHien != value))
				{
					this._NguoiThucHien = value;
				}
			}
		}
	}
	
	public partial class sp_tblcvCongViecCaNhanGiaHan_DanhSachResult
	{
		
		private decimal _MaCongViecCaNhan;
		
		private System.Nullable<System.DateTime> _HanNgayCu;
		
		private System.Nullable<System.TimeSpan> _HanGioCu;
		
		private System.Nullable<System.DateTime> _HanNgayMoi;
		
		private System.Nullable<System.TimeSpan> _HanGioMoi;
		
		private System.Nullable<short> _LanGiaHan;
		
		private string _LyDo;
		
		private System.Nullable<System.DateTime> _NgayThucHien;
		
		private System.Nullable<System.Guid> _NguoiThucHien;
		
		private string _TenNguoiThucHien;
		
		public sp_tblcvCongViecCaNhanGiaHan_DanhSachResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongViecCaNhan", DbType="Decimal(20,0) NOT NULL")]
		public decimal MaCongViecCaNhan
		{
			get
			{
				return this._MaCongViecCaNhan;
			}
			set
			{
				if ((this._MaCongViecCaNhan != value))
				{
					this._MaCongViecCaNhan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanNgayCu", DbType="Date")]
		public System.Nullable<System.DateTime> HanNgayCu
		{
			get
			{
				return this._HanNgayCu;
			}
			set
			{
				if ((this._HanNgayCu != value))
				{
					this._HanNgayCu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanGioCu", DbType="Time")]
		public System.Nullable<System.TimeSpan> HanGioCu
		{
			get
			{
				return this._HanGioCu;
			}
			set
			{
				if ((this._HanGioCu != value))
				{
					this._HanGioCu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanNgayMoi", DbType="Date")]
		public System.Nullable<System.DateTime> HanNgayMoi
		{
			get
			{
				return this._HanNgayMoi;
			}
			set
			{
				if ((this._HanNgayMoi != value))
				{
					this._HanNgayMoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanGioMoi", DbType="Time")]
		public System.Nullable<System.TimeSpan> HanGioMoi
		{
			get
			{
				return this._HanGioMoi;
			}
			set
			{
				if ((this._HanGioMoi != value))
				{
					this._HanGioMoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanGiaHan", DbType="SmallInt")]
		public System.Nullable<short> LanGiaHan
		{
			get
			{
				return this._LanGiaHan;
			}
			set
			{
				if ((this._LanGiaHan != value))
				{
					this._LanGiaHan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LyDo", DbType="NVarChar(250)")]
		public string LyDo
		{
			get
			{
				return this._LyDo;
			}
			set
			{
				if ((this._LyDo != value))
				{
					this._LyDo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThucHien", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayThucHien
		{
			get
			{
				return this._NgayThucHien;
			}
			set
			{
				if ((this._NgayThucHien != value))
				{
					this._NgayThucHien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThucHien", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> NguoiThucHien
		{
			get
			{
				return this._NguoiThucHien;
			}
			set
			{
				if ((this._NguoiThucHien != value))
				{
					this._NguoiThucHien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiThucHien", DbType="NVarChar(50)")]
		public string TenNguoiThucHien
		{
			get
			{
				return this._TenNguoiThucHien;
			}
			set
			{
				if ((this._TenNguoiThucHien != value))
				{
					this._TenNguoiThucHien = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
