<?xml version="1.0" encoding="utf-8"?><Database Name="BSCKPI" Class="linqCongViecCaNhanDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.200.160;Initial Catalog=BSCKPI;Persist Security Info=True;User ID=chay" SettingsObjectName="DaoBSCKPI.Properties.Settings" SettingsPropertyName="BSCKPIConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_tblcvCongViecCaNhan_DanhGiaKetQua" Method="sp_tblcvCongViecCaNhan_DanhGiaKetQua">
    <Parameter Name="Ma" Parameter="ma" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IDTrangThai" Parameter="iDTrangThai" Type="System.Int32" DbType="Int" />
    <Parameter Name="DaHoanThanh" Parameter="daHoanThanh" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NguoiDanhGia" Parameter="nguoiDanhGia" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="MucDoHoanThanh" Parameter="mucDoHoanThanh" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="KetQuaHoanThanh" Parameter="ketQuaHoanThanh" Type="System.String" DbType="NVarChar(500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblcvCongViecCaNhan_ThongTin" Method="sp_tblcvCongViecCaNhan_ThongTin">
    <Parameter Name="Ma" Parameter="ma" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="sp_tblcvCongViecCaNhan_ThongTinResult">
      <Column Name="Ma" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NguoiGiaoViec" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="NguoiTheoDoi" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="NgayGiaoViec" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayDenHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioDenHan" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="IDMucDo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NguoiLamChinh" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ChiDaoChung" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="MaCongViecDonVi" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IDKPI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDDonVi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDPhongBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDTrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DaHoanThanh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NguoiDanhGia" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="NgayDanhGia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MucDoHoanThanh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="KetQuaHoanThanh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblcvCongViecCaNhan_ThemSua" Method="sp_tblcvCongViecCaNhan_ThemSua">
    <Parameter Name="Ma" Parameter="ma" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NoiDung" Parameter="noiDung" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="NguoiGiaoViec" Parameter="nguoiGiaoViec" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="NguoiTheoDoi" Parameter="nguoiTheoDoi" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="NgayGiaoViec" Parameter="ngayGiaoViec" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NgayDenHan" Parameter="ngayDenHan" Type="System.DateTime" DbType="Date" />
    <Parameter Name="GioDenHan" Parameter="gioDenHan" Type="System.TimeSpan" DbType="Time" />
    <Parameter Name="IDMucDo" Parameter="iDMucDo" Type="System.Int32" DbType="Int" />
    <Parameter Name="NguoiLamChinh" Parameter="nguoiLamChinh" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="ChiDaoChung" Parameter="chiDaoChung" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="MaCongViecDonVi" Parameter="maCongViecDonVi" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IDKPI" Parameter="iDKPI" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDDonVi" Parameter="iDDonVi" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDPhongBan" Parameter="iDPhongBan" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDTrangThai" Parameter="iDTrangThai" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblcvCongViecCaNhan_ThemSuaResult">
      <Column Name="MaCongViec" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblcvCongViecCaNhan_DanhSach" Method="sp_tblcvCongViecCaNhan_DanhSach">
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IDDonVi" Parameter="iDDonVi" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDPhongBan" Parameter="iDPhongBan" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_tblcvCongViecCaNhan_DanhSachResult">
      <Column Name="STT" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Ma" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="NguoiGiaoViec" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TenNguoiGiaoViec" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NguoiLamChinh" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TenNguoiLamChinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayGiaoViec" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayDenHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioDenHan" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IDMucDo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MucDo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDTrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuaHan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ThoiGianQuaHan" Type="System.String" DbType="NVarChar(55)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>