#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoBSCKPI.Database.CongViecCaNhan
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BSCKPI")]
	public partial class linqcvcnQuaTrinhXuLyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public linqcvcnQuaTrinhXuLyDataContext() : 
				base(global::DaoBSCKPI.Properties.Settings.Default.BSCKPIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linqcvcnQuaTrinhXuLyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqcvcnQuaTrinhXuLyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqcvcnQuaTrinhXuLyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqcvcnQuaTrinhXuLyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblcvCongViecCaNhanQuaTrinhXuLy_DanhSach")]
		public ISingleResult<sp_tblcvCongViecCaNhanQuaTrinhXuLy_DanhSachResult> sp_tblcvCongViecCaNhanQuaTrinhXuLy_DanhSach([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaCongViecCaNhan", DbType="Decimal(20,0)")] System.Nullable<decimal> maCongViecCaNhan)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCongViecCaNhan);
			return ((ISingleResult<sp_tblcvCongViecCaNhanQuaTrinhXuLy_DanhSachResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblcvCongViecCaNhanQuaTrinhXuLy_ThongTin")]
		public ISingleResult<sp_tblcvCongViecCaNhanQuaTrinhXuLy_ThongTinResult> sp_tblcvCongViecCaNhanQuaTrinhXuLy_ThongTin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaCongViecCaNhan", DbType="Decimal(20,0)")] System.Nullable<decimal> maCongViecCaNhan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDNguoiXuLy", DbType="UniqueIdentifier")] System.Nullable<System.Guid> iDNguoiXuLy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCongViecCaNhan, iDNguoiXuLy);
			return ((ISingleResult<sp_tblcvCongViecCaNhanQuaTrinhXuLy_ThongTinResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tblcvCongViecCaNhanQuaTrinhXuLy_ThemSua")]
		public int sp_tblcvCongViecCaNhanQuaTrinhXuLy_ThemSua([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaCongViecCaNhan", DbType="Decimal(20,0)")] System.Nullable<decimal> maCongViecCaNhan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDNguoiXuLy", DbType="UniqueIdentifier")] System.Nullable<System.Guid> iDNguoiXuLy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDHuongXuLy", DbType="Int")] System.Nullable<int> iDHuongXuLy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoiDungXuLy", DbType="NVarChar(1000)")] string noiDungXuLy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="YKienChiDao", DbType="NVarChar(500)")] string yKienChiDao)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCongViecCaNhan, iDNguoiXuLy, iDHuongXuLy, noiDungXuLy, yKienChiDao);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class sp_tblcvCongViecCaNhanQuaTrinhXuLy_DanhSachResult
	{
		
		private System.Nullable<decimal> _MaCongViecCaNhan;
		
		private System.Nullable<System.Guid> _IDNguoiXuLy;
		
		private string _NguoiThucHien;
		
		private System.Nullable<System.DateTime> _NgayXuLy;
		
		private System.Nullable<int> _IDHuongXuLy;
		
		private string _HuongXuLy;
		
		private string _NoiDungXuLy;
		
		private string _YKienChiDao;
		
		public sp_tblcvCongViecCaNhanQuaTrinhXuLy_DanhSachResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongViecCaNhan", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> MaCongViecCaNhan
		{
			get
			{
				return this._MaCongViecCaNhan;
			}
			set
			{
				if ((this._MaCongViecCaNhan != value))
				{
					this._MaCongViecCaNhan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNguoiXuLy", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> IDNguoiXuLy
		{
			get
			{
				return this._IDNguoiXuLy;
			}
			set
			{
				if ((this._IDNguoiXuLy != value))
				{
					this._IDNguoiXuLy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiThucHien", DbType="NVarChar(50)")]
		public string NguoiThucHien
		{
			get
			{
				return this._NguoiThucHien;
			}
			set
			{
				if ((this._NguoiThucHien != value))
				{
					this._NguoiThucHien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXuLy", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayXuLy
		{
			get
			{
				return this._NgayXuLy;
			}
			set
			{
				if ((this._NgayXuLy != value))
				{
					this._NgayXuLy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHuongXuLy", DbType="Int")]
		public System.Nullable<int> IDHuongXuLy
		{
			get
			{
				return this._IDHuongXuLy;
			}
			set
			{
				if ((this._IDHuongXuLy != value))
				{
					this._IDHuongXuLy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HuongXuLy", DbType="NVarChar(50)")]
		public string HuongXuLy
		{
			get
			{
				return this._HuongXuLy;
			}
			set
			{
				if ((this._HuongXuLy != value))
				{
					this._HuongXuLy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungXuLy", DbType="NVarChar(1000)")]
		public string NoiDungXuLy
		{
			get
			{
				return this._NoiDungXuLy;
			}
			set
			{
				if ((this._NoiDungXuLy != value))
				{
					this._NoiDungXuLy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YKienChiDao", DbType="NVarChar(500)")]
		public string YKienChiDao
		{
			get
			{
				return this._YKienChiDao;
			}
			set
			{
				if ((this._YKienChiDao != value))
				{
					this._YKienChiDao = value;
				}
			}
		}
	}
	
	public partial class sp_tblcvCongViecCaNhanQuaTrinhXuLy_ThongTinResult
	{
		
		private System.Nullable<decimal> _MaCongViecCaNhan;
		
		private System.Nullable<System.Guid> _IDNguoiXuLy;
		
		private System.Nullable<System.DateTime> _NgayXuLy;
		
		private System.Nullable<int> _IDHuongXuLy;
		
		private string _NoiDungXuLy;
		
		private string _YKienChiDao;
		
		public sp_tblcvCongViecCaNhanQuaTrinhXuLy_ThongTinResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongViecCaNhan", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> MaCongViecCaNhan
		{
			get
			{
				return this._MaCongViecCaNhan;
			}
			set
			{
				if ((this._MaCongViecCaNhan != value))
				{
					this._MaCongViecCaNhan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNguoiXuLy", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> IDNguoiXuLy
		{
			get
			{
				return this._IDNguoiXuLy;
			}
			set
			{
				if ((this._IDNguoiXuLy != value))
				{
					this._IDNguoiXuLy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXuLy", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayXuLy
		{
			get
			{
				return this._NgayXuLy;
			}
			set
			{
				if ((this._NgayXuLy != value))
				{
					this._NgayXuLy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHuongXuLy", DbType="Int")]
		public System.Nullable<int> IDHuongXuLy
		{
			get
			{
				return this._IDHuongXuLy;
			}
			set
			{
				if ((this._IDHuongXuLy != value))
				{
					this._IDHuongXuLy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungXuLy", DbType="NVarChar(1000)")]
		public string NoiDungXuLy
		{
			get
			{
				return this._NoiDungXuLy;
			}
			set
			{
				if ((this._NoiDungXuLy != value))
				{
					this._NoiDungXuLy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YKienChiDao", DbType="NVarChar(500)")]
		public string YKienChiDao
		{
			get
			{
				return this._YKienChiDao;
			}
			set
			{
				if ((this._YKienChiDao != value))
				{
					this._YKienChiDao = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
