<?xml version="1.0" encoding="utf-8"?><Database Name="BSCKPI" Class="linqMoHinhDonViDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.200.160;Initial Catalog=BSCKPI;Persist Security Info=True;User ID=chay" SettingsObjectName="DaoBSCKPI.Properties.Settings" SettingsPropertyName="BSCKPIConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_tblMoHinhDonVi_SuaDenNgay" Method="sp_tblMoHinhDonVi_SuaDenNgay">
    <Parameter Name="IDDonVi" Parameter="iDDonVi" Type="System.Int32" DbType="Int" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblMoHinhDonVi_ThemSua" Method="sp_tblMoHinhDonVi_ThemSua">
    <Parameter Name="IDDonVi" Parameter="iDDonVi" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDDonViQuanLy" Parameter="iDDonViQuanLy" Type="System.Int32" DbType="Int" />
    <Parameter Name="STTsx" Parameter="sTTsx" Type="System.Decimal" DbType="Decimal(8,1)" />
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="GhiChu" Parameter="ghiChu" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="NguoiTao" Parameter="nguoiTao" Type="System.String" DbType="NVarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblMoHinhDonVi_ThongTin" Method="sp_tblMoHinhDonVi_ThongTin">
    <Parameter Name="IDDonVi" Parameter="iDDonVi" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ngay" Parameter="ngay" Type="System.DateTime" DbType="Date" />
    <ElementType Name="sp_tblMoHinhDonVi_ThongTinResult">
      <Column Name="IDDonVi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDDonViQuanLy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="STTsx" Type="System.Decimal" DbType="Decimal(8,1)" CanBeNull="true" />
      <Column Name="TuNgay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DenNgay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NguoiTao" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblMoHinhDonVi_DanhSach" Method="sp_tblMoHinhDonVi_DanhSach">
    <Parameter Name="IDDonViQuanLy" Parameter="iDDonViQuanLy" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ngay" Parameter="ngay" Type="System.DateTime" DbType="Date" />
    <ElementType Name="sp_tblMoHinhDonVi_DanhSachResult">
      <Column Name="IDDonVi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDDonViQuanLy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="STTsx" Type="System.Decimal" DbType="Decimal(8,1)" CanBeNull="true" />
      <Column Name="TuNgay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DenNgay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NguoiTao" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>